### ISSUE TITLE
method A not clear?

### ISSUE THREAD

**Issue by neosin** [ikkez/f3-pagination#1]
> Method A: Custom Tag
> The easiest way to create the pagebrowser now, is to use the custom template tag renderer. This generates the pagebrowser directly from the inside of your template. Therefor just register the pagebrowser right at the start in your index.php:

In the above text, it is not clear which index.php file is being referred to. Is this the index.php where we initialize and load F3? Is it the controller or the model or perhaps even the view?
Currently using Method B because it is much clearer but requires more code in the controller.

**Comment by ikkez** [comment]
Well you can put this nearly anywhere, as long as the tag component is registered to the Template instance before you start rendering a template with it. This can be in your front-controller (main index.php) your page controller, view or however your system is built.
